# Generated by Django 3.2.9 on 2021-12-01 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_link', models.TextField(verbose_name='Topic link')),
                ('img_link', models.TextField(verbose_name='Image link')),
                ('title', models.TextField(verbose_name='Title of the topic')),
                ('article_date', models.DateField(verbose_name='Date of article publication')),
                ('article_author', models.TextField(verbose_name='Article author')),
                ('tags', models.TextField(verbose_name='Tags')),
                ('text', models.TextField(verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User login')),
            ],
            options={
                'ordering': ['-article_date'],
            },
        ),
    ]
