# Generated by Django 3.2.9 on 2021-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.AddField(
            model_name='page',
            name='img_link',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='page',
            name='topic_link',
            field=models.TextField(default='none'),
        ),
    ]
