# Generated by Django 3.2.9 on 2021-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20211124_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='topic_link',
            field=models.TextField(),
        ),
    ]
