# Generated by Django 3.2.9 on 2021-11-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20211124_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
    ]
